version: '3'
networks:
  mongo:
  web:
services:
  db:
    image: mongo:4.2
    networks:
      - mongo
    ports:
      - 27017:27017
  backend:
    image: node:8.16
    volumes:
      - ./backend:/usr/task-app
      - /usr/task-app/node_modules
    networks:
      - web
      - mongo
    depends_on:
      - db
    ports:
      - 3000:3000
    working_dir: /usr/task-app
  command: bash -c "npm i && npm run dev"
